### ISSUE TITLE
Build is failing can't figure out why.

### ISSUE THREAD

**Issue by shortthefomo** [Xahau/xahaud#380]
```
[ 54%] Performing update step for 'grpc_src'
-- Already at requested tag: v1.25.0
[ 55%] No patch step for 'grpc_src'
[ 55%] Performing configure step for 'grpc_src'
CMake Warning (dev) at /Volumes/Dev/Web3/XAHAU/xahaud/.nih_c/unix_makefiles/AppleClang_14.0.3.14030022/Debug/src/grpc_src-stamp/grpc_src-configure-Debug.cmake:7:
  Syntax Warning in cmake code at column 419

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- grpc_src configure command succeeded.  See also /Volumes/Dev/Web3/XAHAU/xahaud/.nih_c/unix_makefiles/AppleClang_14.0.3.14030022/Debug/src/grpc_src-stamp/grpc_src-configure-*.log
[ 56%] Performing build step for 'grpc_src'
-- grpc_src build command succeeded.  See also /Volumes/Dev/Web3/XAHAU/xahaud/.nih_c/unix_makefiles/AppleClang_14.0.3.14030022/Debug/src/grpc_src-stamp/grpc_src-build-*.log
[ 57%] No install step for 'grpc_src'
[ 58%] No test step for 'grpc_src'
[ 59%] Completed 'grpc_src'
[ 59%] Built target grpc_src
make[1]: *** [CMakeFiles/rippled.dir/rule] Error 2
make: *** [rippled] Error 2
```

**Comment by shortthefomo** [comment]
@dangell7 helped a bit due to build only really working on linux at the moment.
`error: no viable conversion from returned value of type 'bool' to function return type 'std::strong_ordering'
    return std::lexicographical_compare_three_way(`

was the error it was tripping up on, that bing said even commenting out that bit still did not get me much further as then the next one popped up

`error: invalid operands to binary expression ('const base_uint<128UL, void>' and 'const base_uint<128UL, void>')
    return (lhs <=> rhs) == 0;`

 https://github.com/XRPLF/rippled/pull/4411 

know back porting support on its way so prob just close this one out?

**Comment by tequdev** [comment]
I encountered the same problem, but solved it by uncommenting L552-L574 in base_unit and commenting out L576-586.

https://github.com/Xahau/xahaud/blob/6b26045cbce373388c8cd7603968d5612f531c08/src/ripple/basics/base_uint.h#L552-L586

It could be a problem caused by the following PR
https://github.com/Xahau/xahaud/pull/374

**Comment by RichardAH** [comment]
Can someone confirm this is fixed now?

**Comment by shortthefomo** [comment]
assume one needs to check the dev branch and latest from there its still failing for me.

```In file included from /Volumes/Dev/Web3/XAHAU/xahaud/build/CMakeFiles/rippled.dir/Unity/unity_8_cxx.cxx:19:
/Volumes/Dev/Web3/XAHAU/xahaud/src/ripple/basics/impl/make_SSLContext.cpp:94:20: warning: 'RSA_new' is deprecated [-Wdeprecated-declarations]
        auto rsa = RSA_new();
                   ^
/opt/homebrew/opt/openssl@3/include/openssl/rsa.h:212:1: note: 'RSA_new' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 RSA *RSA_new(void);
^
/opt/homebrew/opt/openssl@3/include/openssl/macros.h:194:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/opt/homebrew/opt/openssl@3/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
In file included from /Volumes/Dev/Web3/XAHAU/xahaud/build/CMakeFiles/rippled.dir/Unity/unity_8_cxx.cxx:19:
/Volumes/Dev/Web3/XAHAU/xahaud/src/ripple/basics/impl/make_SSLContext.cpp:99:13: warning: 'RSA_generate_key_ex' is deprecated [-Wdeprecated-declarations]
        if (RSA_generate_key_ex(rsa, defaultRSAKeyBits, bn, nullptr) != 1)
            ^
/opt/homebrew/opt/openssl@3/include/openssl/rsa.h:271:1: note: 'RSA_generate_key_ex' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int RSA_generate_key_ex(RSA *rsa, int bits, BIGNUM *e,
^
/opt/homebrew/opt/openssl@3/include/openssl/macros.h:194:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/opt/homebrew/opt/openssl@3/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
In file included from /Volumes/Dev/Web3/XAHAU/xahaud/build/CMakeFiles/rippled.dir/Unity/unity_8_cxx.cxx:19:
/Volumes/Dev/Web3/XAHAU/xahaud/src/ripple/basics/impl/make_SSLContext.cpp:115:13: warning: 'RSA_up_ref' is deprecated [-Wdeprecated-declarations]
        if (RSA_up_ref(defaultRSA) != 1)
            ^
/opt/homebrew/opt/openssl@3/include/openssl/rsa.h:306:1: note: 'RSA_up_ref' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int RSA_up_ref(RSA *r);
^
/opt/homebrew/opt/openssl@3/include/openssl/macros.h:194:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/opt/homebrew/opt/openssl@3/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
In file included from /Volumes/Dev/Web3/XAHAU/xahaud/build/CMakeFiles/rippled.dir/Unity/unity_8_cxx.cxx:19:
/Volumes/Dev/Web3/XAHAU/xahaud/src/ripple/basics/impl/make_SSLContext.cpp:119:14: warning: 'EVP_PKEY_assign' is deprecated [-Wdeprecated-declarations]
        if (!EVP_PKEY_assign_RSA(pkey, defaultRSA))
             ^
/opt/homebrew/opt/openssl@3/include/openssl/evp.h:501:41: note: expanded from macro 'EVP_PKEY_assign_RSA'
#  define EVP_PKEY_assign_RSA(pkey,rsa) EVP_PKEY_assign((pkey),EVP_PKEY_RSA,\
                                        ^
/opt/homebrew/opt/openssl@3/include/openssl/evp.h:1337:1: note: 'EVP_PKEY_assign' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0
^
/opt/homebrew/opt/openssl@3/include/openssl/macros.h:194:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/opt/homebrew/opt/openssl@3/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
In file included from /Volumes/Dev/Web3/XAHAU/xahaud/build/CMakeFiles/rippled.dir/Unity/unity_6_cxx.cxx:16:
/Volumes/Dev/Web3/XAHAU/xahaud/src/ripple/app/tx/impl/Escrow.cpp:449:47: warning: '&&' within '||' [-Wlogical-op-parentheses]
            ctx.tx.isFieldPresent(sfEscrowID) &&
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/Volumes/Dev/Web3/XAHAU/xahaud/src/ripple/app/tx/impl/Escrow.cpp:449:47: note: place parentheses around the '&&' expression to silence this warning
            ctx.tx.isFieldPresent(sfEscrowID) &&
                                              ^
            (
/Volumes/Dev/Web3/XAHAU/xahaud/src/ripple/app/tx/impl/Escrow.cpp:732:47: warning: '&&' within '||' [-Wlogical-op-parentheses]
            ctx.tx.isFieldPresent(sfEscrowID) &&
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/Volumes/Dev/Web3/XAHAU/xahaud/src/ripple/app/tx/impl/Escrow.cpp:732:47: note: place parentheses around the '&&' expression to silence this warning
            ctx.tx.isFieldPresent(sfEscrowID) &&
                                              ^
            (
In file included from /Volumes/Dev/Web3/XAHAU/xahaud/build/CMakeFiles/rippled.dir/Unity/unity_12_cxx.cxx:7:
/Volumes/Dev/Web3/XAHAU/xahaud/src/ripple/nodestore/impl/Shard.cpp:715:35: error: use of undeclared identifier 'XRP_LEDGER_EARLIEST_FEES'; did you mean 'XRP_LEDGER_EARLIEST_SEQ'?
            (ledger->info().seq < XRP_LEDGER_EARLIEST_FEES ||
                                  ^~~~~~~~~~~~~~~~~~~~~~~~
                                  XRP_LEDGER_EARLIEST_SEQ
/Applications/Xcode_14.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
                        ^
/Volumes/Dev/Web3/XAHAU/xahaud/src/ripple/protocol/SystemParameters.h:69:32: note: 'XRP_LEDGER_EARLIEST_SEQ' declared here
static constexpr std::uint32_t XRP_LEDGER_EARLIEST_SEQ{1U};
                               ^
In file included from /Volumes/Dev/Web3/XAHAU/xahaud/build/CMakeFiles/rippled.dir/Unity/unity_34_cxx.cxx:16:
/Volumes/Dev/Web3/XAHAU/xahaud/src/test/rpc/AccountNamespace_test.cpp:113:24: warning: unused variable 'key' [-Wunused-variable]
            auto const key = uint256::fromVoid(
                       ^
/Volumes/Dev/Web3/XAHAU/xahaud/src/test/rpc/AccountNamespace_test.cpp:129:24: warning: unused variable 'nons' [-Wunused-variable]
            auto const nons = uint256::fromVoid(
                       ^
In file included from /Volumes/Dev/Web3/XAHAU/xahaud/build/CMakeFiles/rippled.dir/Unity/unity_5_cxx.cxx:7:
In file included from /Volumes/Dev/Web3/XAHAU/xahaud/src/ripple/app/rdb/impl/RelationalDatabase.cpp:23:
/Volumes/Dev/Web3/XAHAU/xahaud/src/ripple/app/rdb/backend/RWDBDatabase.h:797:23: warning: unused variable 'queryLimit' [-Wunused-variable]
        std::uint32_t queryLimit = numberOfResults + 1;
                      ^
In file included from /Volumes/Dev/Web3/XAHAU/xahaud/build/CMakeFiles/rippled.dir/Unity/unity_23_cxx.cxx:25:
/Volumes/Dev/Web3/XAHAU/xahaud/src/test/app/SetHook_test.cpp:1095:20: warning: unused variable 'preOwnerCount' [-Wunused-variable]
        auto const preOwnerCount = (*env.le(alice))[sfOwnerCount];
                   ^
2 warnings generated.
/Volumes/Dev/Web3/XAHAU/xahaud/src/test/app/SetHook_test.cpp:5848:9: warning: unused variable 'checker_keylet' [-Wunused-variable]
        HASH_WASM(checker);
        ^
/Volumes/Dev/Web3/XAHAU/xahaud/src/test/app/SetHook_test.cpp:75:18: note: expanded from macro 'HASH_WASM'
    Keylet const x##_keylet = keylet::hookDefinition(x##_hash);
                 ^
<scratch space>:51:1: note: expanded from here
checker_keylet
^
In file included from /Volumes/Dev/Web3/XAHAU/xahaud/build/CMakeFiles/rippled.dir/Unity/unity_23_cxx.cxx:25:
/Volumes/Dev/Web3/XAHAU/xahaud/src/test/app/SetHook_test.cpp:6042:9: warning: unused variable 'pos_keylet' [-Wunused-variable]
        HASH_WASM(pos);
        ^
/Volumes/Dev/Web3/XAHAU/xahaud/src/test/app/SetHook_test.cpp:75:18: note: expanded from macro 'HASH_WASM'
    Keylet const x##_keylet = keylet::hookDefinition(x##_hash);
                 ^
<scratch space>:72:1: note: expanded from here
pos_keylet
^
In file included from /Volumes/Dev/Web3/XAHAU/xahaud/build/CMakeFiles/rippled.dir/Unity/unity_3_cxx.cxx:7:
/Volumes/Dev/Web3/XAHAU/xahaud/src/ripple/app/misc/SHAMapStoreImp.cpp:298:16: warning: unused variable 'isMem' [-Wunused-variable]
    bool const isMem = app_.config().mem_backend();
               ^
In file included from /Volumes/Dev/Web3/XAHAU/xahaud/build/CMakeFiles/rippled.dir/Unity/unity_23_cxx.cxx:25:
/Volumes/Dev/Web3/XAHAU/xahaud/src/test/app/SetHook_test.cpp:8367:9: warning: unused variable 'grantee_keylet' [-Wunused-variable]
        HASH_WASM(grantee);
        ^
/Volumes/Dev/Web3/XAHAU/xahaud/src/test/app/SetHook_test.cpp:75:18: note: expanded from macro 'HASH_WASM'
    Keylet const x##_keylet = keylet::hookDefinition(x##_hash);
                 ^
<scratch space>:15:1: note: expanded from here
grantee_keylet
^
In file included from /Volumes/Dev/Web3/XAHAU/xahaud/build/CMakeFiles/rippled.dir/Unity/unity_23_cxx.cxx:25:
/Volumes/Dev/Web3/XAHAU/xahaud/src/test/app/SetHook_test.cpp:8419:9: warning: unused variable 'grantor_keylet' [-Wunused-variable]
        HASH_WASM(grantor);
        ^
/Volumes/Dev/Web3/XAHAU/xahaud/src/test/app/SetHook_test.cpp:75:18: note: expanded from macro 'HASH_WASM'
    Keylet const x##_keylet = keylet::hookDefinition(x##_hash);
                 ^
<scratch space>:22:1: note: expanded from here
grantor_keylet
^
In file included from /Volumes/Dev/Web3/XAHAU/xahaud/build/CMakeFiles/rippled.dir/Unity/unity_23_cxx.cxx:25:
/Volumes/Dev/Web3/XAHAU/xahaud/src/test/app/SetHook_test.cpp:8681:9: warning: unused variable 'exhaustion_keylet' [-Wunused-variable]
        HASH_WASM(exhaustion);
        ^
/Volumes/Dev/Web3/XAHAU/xahaud/src/test/app/SetHook_test.cpp:75:18: note: expanded from macro 'HASH_WASM'
    Keylet const x##_keylet = keylet::hookDefinition(x##_hash);
                 ^
<scratch space>:71:1: note: expanded from here
exhaustion_keylet
^
In file included from /Volumes/Dev/Web3/XAHAU/xahaud/build/CMakeFiles/rippled.dir/Unity/unity_23_cxx.cxx:25:
/Volumes/Dev/Web3/XAHAU/xahaud/src/test/app/SetHook_test.cpp:9376:9: warning: unused variable 'exhaustion_keylet' [-Wunused-variable]
        HASH_WASM(exhaustion);
        ^
/Volumes/Dev/Web3/XAHAU/xahaud/src/test/app/SetHook_test.cpp:75:18: note: expanded from macro 'HASH_WASM'
    Keylet const x##_keylet = keylet::hookDefinition(x##_hash);
                 ^
<scratch space>:29:1: note: expanded from here
exhaustion_keylet
^
4 warnings generated.
In file included from /Volumes/Dev/Web3/XAHAU/xahaud/build/CMakeFiles/rippled.dir/Unity/unity_5_cxx.cxx:7:
In file included from /Volumes/Dev/Web3/XAHAU/xahaud/src/ripple/app/rdb/impl/RelationalDatabase.cpp:22:
/Volumes/Dev/Web3/XAHAU/xahaud/src/ripple/app/rdb/backend/FlatmapDatabase.h:55:19: warning: private field 'config_' is not used [-Wunused-private-field]
    Config const& config_;
                  ^
/Volumes/Dev/Web3/XAHAU/xahaud/src/ripple/app/rdb/backend/FlatmapDatabase.h:56:15: warning: private field 'jobQueue_' is not used [-Wunused-private-field]
    JobQueue& jobQueue_;
              ^
2 warnings generated.
1 error generated.
make[3]: *** [CMakeFiles/rippled.dir/Unity/unity_12_cxx.cxx.o] Error 1
make[3]: *** Waiting for unfinished jobs....
3 warnings generated.
7 warnings generated.
1 warning generated.
In file included from /Volumes/Dev/Web3/XAHAU/xahaud/build/CMakeFiles/rippled.dir/Unity/unity_16_cxx.cxx:37:
/Volumes/Dev/Web3/XAHAU/xahaud/src/ripple/rpc/handlers/ServerDefinitions.cpp:470:20: warning: returning reference to local temporary object [-Wreturn-stack-address]
            return uint256(
                   ^~~~~~~~
1 warning generated.
make[2]: *** [CMakeFiles/rippled.dir/all] Error 2
make[1]: *** [CMakeFiles/rippled.dir/rule] Error 2
make: *** [rippled] Error 2
```

**Comment by dangell7** [comment]
@shortthefomo can you try pulling this branch and building?

https://github.com/Xahau/xahaud/pull/397

**Comment by shortthefomo** [comment]
using https://github.com/Xahau/xahaud/pull/397

<img width="204" alt="Screenshot 2024-11-26 at 10 23 50 AM" src="https://github.com/user-attachments/assets/2cfd921d-f993-4c18-b401-7c87c36f660c">

awesome now its building for me !
